### ISSUE TITLE
Change Database for setup

### ISSUE THREAD

**Issue by likeadeckofcards** [Qoraiche/laravel-mail-editor#21]
Hello @Qoraiche,

This package looks great. I did notice one issue. When it runs through each factory, it is creating and storing the items in the application's database and not a testing location like a sqlite DB or different database. 

This might be what @kertul is referring to in #19.

Thank you,
Michael D.

**Comment by Qoraiche** [comment]
Hello @infernobass7,

I think we have this discussed this problem before in the https://github.com/Qoraiche/laravel-mail-editor/issues/8 issue and I fixed it in the **v1.1.3** version by rolling back database each time a factory runs (check out this commit https://github.com/Qoraiche/laravel-mail-editor/commit/97a764aea8535fd0ec294a240f0124882a9d8399).

**Comment by infernobass7** [comment]
Hello @Qoraiche I am using v1.1.5 and the database is still persisting from the tests that run each time you hit the maileclipse dashboard.

**Comment by Qoraiche** [comment]
@infernobass7 weird, did you try to clear your database and try again? also what DB connection are you using?

**Comment by infernobass7** [comment]
@Qoraiche we are using mysql database and after clearing out the new models from the database I still get new models created even with the newest version of this package.

**Comment by infernobass7** [comment]
@Qoraiche Please reopen.

**Comment by Qoraiche** [comment]
Can you share your mailable please? also what models are you using?

**Comment by infernobass7** [comment]
```php
<?php

namespace App\Mail;

use App\Document;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Support\Facades\Auth;

class ProposalCreated extends Mailable {
	use Queueable, SerializesModels;

	public $document;

	public function __construct(Document $document) {
		$this->document = $document->load(['user', 'line_items']);
	}

	public function build() {
		if(Auth::check()) {
			$user = Auth::user();
			$this->from($user->email, $user->name);
		}

		return $this->view('emails.proposal-created')
			->text('emails.plain.proposal-created')
			->attachData($this->document->pdf('string'), "proposal-{$this->document->number}.pdf", [
				'mime' => 'application/pdf',
			]);
	}
}

```

**Comment by Qoraiche** [comment]
Hello @infernobass7, sorry for the late reply,

Unfortunately, I can't reproduce your issue, looks like it's a problem with "Lazy" eager loading ` $document->load(['user', 'line_items']);` i will do more tests, and i hope this will be fixed in the next updates.

Thanks.

**Comment by ReeceM** [comment]
Currently with regards to the issue #63, this usage of a separate table for testing might be of use as it will be loading relations internally of the package for calls to relations if they exist and generate factory values.

I am also thinking that this would require the install command to run the `artisan:migrate` command so as to insure that the SQLite database is synchronized with the actual DB although if there is an issue, we can make use of ignition error pages to inform someone that the DB is out of sync and provide a solution. 

Although we could make use of the schema and check if there is something that doesn't match and redirect the user.

Overall, this does seem like a useful option to allow a user to have this available, in that they could activate the use of a separate DB.

@likeadeckofcards thank you for highlighting this 👍

**Comment by WhiskeyM1ke** [comment]
I'm having this same issue.  Each load of MailEclipse creates numerous 'App\Models\User' and numerous 'App\Models\Room' which aren't even related.  The created rows are persisted in the database, and I have to go through each time and run MySQL queries to remove them.

**Comment by ReeceM** [comment]
Hi @WhiskeyM1ke 

Would you be able to let me know what version of Laravel you are using and the version of the package please?

**Comment by WhiskeyM1ke** [comment]
Laravel 8.6 and package ^3.5

I was just embracing it for now, but after creating a Mailable, the package kept loading and created somewhere around 4,000 Users.  Had to close the browser window.

**Comment by ReeceM** [comment]
> Laravel 8.6 and package ^3.5
> 
> I was just embracing it for now, but after creating a Mailable, the package kept loading and created somewhere around 4,000 Users. Had to close the browser window.

Thank you for the info. 

With regards to creating so many users that is strange as I have it installed fresh in a new package and it doesn't have this behavior. I know that there will be newer PK values in a db but it will be clear after the transaction is completed.

Would you be able to create a reproduction repository if this isn't an open source repo I can look at and post it here. It will be the easiest way for me to know what is up with it. And it will let me sort it quicker. 😄

**Comment by WhiskeyM1ke** [comment]
> 
> 
> Would you be able to create a reproduction repository if this isn't an open source repo I can look at and post it here. It will be the easiest way for me to know what is up with it. And it will let me sort it quicker. 😄

Kinda new to git.  I've made my own private project repos (this being one of them).  I'll try to figure out how to do this and get back to you.  Thanks!

**Comment by ReeceM** [comment]
Hi @WhiskeyM1ke sorry that you were running out of time. 

If possible after you have got time you can `git clone` the private repo, then create a new repo on GitHub and set it as public. Don’t initialize with a readme or other stuff. 

Then there is a page that has instructions on adding things to the repo, you will want to use the option for an existing repository. So `git add origin …` and so forth. Then that would be how you can share that 👍

**Comment by angusm73** [comment]
I'm also experiencing this issue. When loading `/maileclipse`, the page returns a 500 error (logs show memory exhausted) and then I check users & regions tables, noticing it has created ~400 rows from factories.

I didn't notice in your source code where it creates models, only saw it call `make()` on the factories. Can take a look at creating a reproduction repo later this week.
